# renew_before_expiry = 30 days
version = 2.10.0
archive_dir = /etc/letsencrypt/archive/astrotech-spaceapp.space
cert = /etc/letsencrypt/live/astrotech-spaceapp.space/cert.pem
privkey = /etc/letsencrypt/live/astrotech-spaceapp.space/privkey.pem
chain = /etc/letsencrypt/live/astrotech-spaceapp.space/chain.pem
fullchain = /etc/letsencrypt/live/astrotech-spaceapp.space/fullchain.pem

# Options used in the renewal process
[renewalparams]
account = e3417b8e48525af94a45bfdc58e212e4
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
astrotech-spaceapp.space = /var/www/certbot
