services:
  nodejs:
    image: ghcr.io/it-lab-tj/marketplace-client-nodejs
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "4200"
      - "3000"
    networks:
      - marketplace-network

  proxy:
    image: ghcr.io/it-lab-tj/marketplace-client-proxy
    build:
      context: ./nginx
      dockerfile: Dockerfile
    volumes:
      - nginx_data:/etc/nginx
      - certbot_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
      - "3000:3000"
    networks:
      - marketplace-network
    depends_on:
      - nodejs
      - cert

  cert:
    image: ghcr.io/it-lab-tj/marketplace-client-cert
    build:
      context: ./certbot
      dockerfile: Dockerfile
      args:
        DOMAIN_EMAIL: ${DOMAIN_EMAIL}
        DOMAIN_URL: ${DOMAIN_URL}
    command: ["sleep", "infinity"]

    env_file:
      - .env
    volumes:
      - certbot_www:/var/www/certbot
      - certbot_data:/etc/letsencrypt
      - nginx_data:/etc/nginx
    expose:
      - "80"
    networks:
      - marketplace-network

  manipulator:
    image: docker:latest
    command: ["sh", "-c", "apk add --no-cache bash dcron && crond && /bin/bash /scripts/certbot_schedule.sh && tail -f /var/log/cron.log"]
    working_dir: /compose_files
    networks:
      - marketplace-network

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

      # nginx_confs_bc - Folder with nginx configs backups
      - ./nginx/default.conf:/nginx_confs_bc/default.conf
      - ./nginx/ssl.conf:/nginx_confs_bc/ssl.conf

      # From here, will manipulate with nginx container
      # configurations from this container.
      - nginx_data:/etc/nginx

      # Mount compose files for composing containers.
      - ./compose.yml:/compose_files/compose.yml
      - ./compose.override.yml:/compose_files/compose.override.yml
      - .env:/compose_files/.env
      - ./certbot/certbot_schedule.sh:/scripts/certbot_schedule.sh
      - ./certbot/certbot_renew.sh:/scripts/certbot_renew.sh

    environment:
      - NGINX_CONTAINER_NAME=proxy
      - CERTBOT_CONTAINER_NAME=cert
      - DOMAIN_URL=${DOMAIN_URL}
      - NGINX_CONF_D=/etc/nginx/conf.d

networks:
  marketplace-network:
    driver: bridge

volumes:
  nginx_data:
  certbot_data:
  certbot_www:
