services:
  api:
    image: ghcr.io/it-lab-tj/marketplace-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${DJANGO_PORT}:8000"
    networks:
      - marketplace
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DB}
    env_file:
      - .env
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - marketplace-db:/var/lib/postgresql/data
    networks:
      - marketplace

  proxy:
    image: ghcr.io/it-lab-tj/marketplace-proxy:latest
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "${PROXY_PORT}:80"
    networks:
      - marketplace
    depends_on:
      - api

networks:
  marketplace:
    driver: bridge

volumes:
  marketplace-db:
    driver: local
