services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${DJANGO_PORT}:8000"
    networks:
      - marketplace
    depends_on:
      - db

  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - marketplace-db:/var/lib/postgresql/data
    networks:
      - marketplace
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "${PROXY_PORT}:80"
    networks:
      - marketplace
    depends_on:
      - api

networks:
  marketplace:
    driver: bridge

volumes:
  marketplace-db:
    driver: local
