services:
  nodejs:
    image: ghcr.io/it-lab-tj/marketplace-client-nodejs
    container_name: frontend_container

  proxy:
    image: ghcr.io/it-lab-tj/marketplace-client-proxy
    container_name: proxy_container

  monipulator:
    image: ghcr.io/it-lab-tj/marketplace-client-manipulator
    container_name: manipulator

  cert:
    image: ghcr.io/it-lab-tj/marketplace-client-certbot
    container_name: certbot
