services:
  nodejs:
    image: ghcr.io/it-lab-tj/marketplace-client-nodejs
    container_name: frontend_container

  proxy:
    image: ghcr.io/it-lab-tj/marketplace-client-proxy
    container_name: proxy_container

  certbot:
    image: ghcr.io/it-lab-tj/marketplace-client-certbot