services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/it-lab-tj/marketplace-client-nodejs:latest
    container_name: marketplace
    networks:
      - marketplace-network
    ports:
      - "4200:4200"
      - "3000:3000"  # Проброс портов на хост-систему

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: ghcr.io/it-lab-tj/marketplace-client-nginx:latest
    container_name: nginx
    ports:
      - "4200:4200"
      - "3000:3000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nodejs
    networks:
      - marketplace-network

  networks:
    marketplace-network:
      driver: bridge