services:
  marketplace:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: marketplace
    expose:
      - "4000"
    networks:
      - marketplace-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - marketplace
    networks:
      - marketplace-network

networks:
  marketplace-network:
    driver: bridge