# Generated by Django 5.0.7 on 2024-11-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_alter_category_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="synced_at",
            field=models.DateTimeField(null=True),
        ),
    ]
