# Generated by Django 5.0.7 on 2024-11-28 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_category_synced_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="synced_at",
        ),
    ]
