# Generated by Django 5.0.7 on 2024-11-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0005_remove_category_ext_parent_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="ext_parent_title",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
