# Generated by Django 5.0.7 on 2024-11-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MKSyncInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cat_synced", models.DateTimeField(null=True)),
                ("prod_synced", models.DateTimeField(null=True)),
                ("synced", models.DateTimeField(null=True)),
            ],
        ),
    ]
