# Generated by Django 5.0.7 on 2024-11-28 10:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moy_sklad", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mksyncinfo",
            old_name="synced",
            new_name="synced_at",
        ),
    ]
