# Generated by Django 5.0.7 on 2024-11-28 10:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("moy_sklad", "0002_rename_synced_mksyncinfo_synced_at"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mksyncinfo",
            old_name="cat_synced",
            new_name="cat_synced_at",
        ),
        migrations.RenameField(
            model_name="mksyncinfo",
            old_name="prod_synced",
            new_name="prod_synced_at",
        ),
    ]
