# Generated by Django 5.0.7 on 2024-09-30 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("gallery", "0004_alter_slide_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Наввание")),
                ("link", models.CharField(max_length=1024, verbose_name="Ссылка")),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="gallery.image",
                        verbose_name="Иконка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
            },
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("address", models.CharField(max_length=256, verbose_name="Адрес")),
                (
                    "phone",
                    models.CharField(max_length=15, verbose_name="Номер телефона"),
                ),
                (
                    "phone_two",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Запасной номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Адрес электронной почты"
                    ),
                ),
                (
                    "coordinates",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Координаты"
                    ),
                ),
                ("about_us", models.TextField(blank=True, null=True)),
                (
                    "icon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gallery.image",
                        verbose_name="Иконка",
                    ),
                ),
                (
                    "social_networks",
                    models.ManyToManyField(
                        to="common.socialmedia", verbose_name="Социальные сети"
                    ),
                ),
            ],
        ),
    ]
