# Generated by Django 5.0.2 on 2024-11-10 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Organization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=256, null=True, verbose_name="Адрес"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Номер телефона",
                    ),
                ),
                (
                    "phone_two",
                    models.CharField(
                        blank=True,
                        max_length=15,
                        null=True,
                        verbose_name="Запасной номер телефона",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Адрес электронной почты",
                    ),
                ),
                (
                    "icon",
                    models.ImageField(
                        blank=True, null=True, upload_to="", verbose_name="Иконка"
                    ),
                ),
                (
                    "coordinates",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Координаты"
                    ),
                ),
                ("about_us", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=1024, verbose_name="Ссылка")),
                (
                    "social_type",
                    models.CharField(
                        choices=[
                            ("youtube", "youtube"),
                            ("twitter", "twitter"),
                            ("instagram", "instagram"),
                            ("linkedin", "linkedin"),
                            ("fb", "facebook"),
                            ("telegram", "telegram"),
                            ("whatsapp", "whatsApp"),
                        ],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть",
                "verbose_name_plural": "Социальные сети",
            },
        ),
    ]
