# Generated by Django 5.0.7 on 2024-09-30 17:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organization",
            options={
                "verbose_name": "Организация",
                "verbose_name_plural": "Организации",
            },
        ),
    ]
