# Generated by Django 5.0.7 on 2024-10-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialmedia",
            name="icon",
        ),
        migrations.AlterField(
            model_name="socialmedia",
            name="social_type",
            field=models.CharField(
                choices=[
                    ("youtube", "youtube"),
                    ("twitter", "twitter"),
                    ("instagram", "instagram"),
                    ("linkedin", "linkedin"),
                    ("fb", "facebook"),
                    ("telegram", "telegram"),
                    ("whatsapp", "whatsApp"),
                ],
                max_length=20,
            ),
        ),
    ]
