# Generated by Django 5.0.7 on 2024-10-19 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "turn",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Очередь"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="", verbose_name="Изображения организации"
                    ),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="Ссылка")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Статус активности"),
                ),
            ],
            options={
                "verbose_name": "Слайд",
                "verbose_name_plural": "Слайды",
                "ordering": ("turn",),
            },
        ),
    ]
