# Generated by Django 5.0.7 on 2024-09-30 03:54

import django.db.models.deletion
import src.apps.gallery.models.image
import src.base.mixins.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название"
                    ),
                ),
                (
                    "original",
                    models.ImageField(
                        upload_to=src.apps.gallery.models.image.upload_to,
                        verbose_name="Оригинальное изображение",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        null=True,
                        unique=True,
                        verbose_name="Ссылка на изображение",
                    ),
                ),
            ],
            bases=(
                models.Model,
                src.base.mixins.models.AbstractAuditModelsFields,
                src.base.mixins.models.AbstractTimestambleModelFields,
            ),
        ),
        migrations.CreateModel(
            name="Slide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "turn",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Очередь"
                    ),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="Ссылка")),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="Статус активности"),
                ),
                (
                    "image",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gallery.image",
                        verbose_name="Слайд",
                    ),
                ),
            ],
            bases=(
                models.Model,
                src.base.mixins.models.AbstractTimestambleModelFields,
                src.base.mixins.models.AbstractAuditModelsFields,
            ),
        ),
    ]
