# Generated by Django 5.0.7 on 2024-09-30 04:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="image",
            old_name="original",
            new_name="image",
        ),
    ]
