# Generated by Django 5.1.1 on 2024-11-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original", models.ImageField(upload_to="", verbose_name="Оригинал")),
                ("url", models.URLField(max_length=550)),
            ],
        ),
    ]
