# Generated by Django 5.0.7 on 2024-11-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="original",
        ),
        migrations.AddField(
            model_name="image",
            name="ext_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="media/images/products",
                verbose_name="Оригинал",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="url",
            field=models.URLField(blank=True, max_length=550, null=True),
        ),
    ]
