# Generated by Django 5.0.7 on 2024-09-30 10:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0002_rename_original_image_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="image",
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.AlterModelOptions(
            name="slide",
            options={
                "ordering": ("turn",),
                "verbose_name": "Слайд",
                "verbose_name_plural": "Слайды",
            },
        ),
    ]
