# Generated by Django 5.0.7 on 2024-09-30 10:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_alter_image_options_alter_slide_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="slide",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="gallery.image",
                verbose_name="Изображение",
            ),
        ),
    ]
