# Generated by Django 5.0.7 on 2024-11-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_remove_image_original_image_ext_id_image_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="products", verbose_name="Оригинал"
            ),
        ),
    ]
