# Generated by Django 5.1.1 on 2024-11-21 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("category", "0002_alter_category_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ext_id",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ID во внешнем сервисе"
                    ),
                ),
                (
                    "ext_parent_title",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Название родительской категории во внешнем сервисе",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена"
                    ),
                ),
                ("images", models.JSONField(verbose_name="Изображения")),
                (
                    "on_sale",
                    models.BooleanField(default=False, verbose_name="В продаже"),
                ),
                (
                    "discount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Скидка",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "count",
                    models.PositiveIntegerField(default=0, verbose_name="Количество"),
                ),
                (
                    "weight",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Вес",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Бренд"
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Модель"
                    ),
                ),
                (
                    "colors",
                    models.JSONField(blank=True, null=True, verbose_name="Цвета"),
                ),
                (
                    "vendor_code",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Артикул"
                    ),
                ),
                (
                    "production_year",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Год выпуска"
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="category.category",
                        verbose_name="Категория",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
