# Generated by Django 5.1.1 on 2024-11-21 13:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="ext_parent_title",
        ),
        migrations.AddField(
            model_name="product",
            name="ext_cat_id",
            field=models.CharField(
                blank=True,
                max_length=50,
                null=True,
                verbose_name="ID категории во внешнем сервисе",
            ),
        ),
    ]
