# Generated by Django 5.1.1 on 2024-11-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_alter_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="model",
            field=models.JSONField(blank=True, null=True, verbose_name="Модели"),
        ),
    ]
