# Generated by Django 5.0.7 on 2024-11-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_alter_product_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="synced",
            field=models.DateTimeField(null=True),
        ),
    ]
