# Generated by Django 5.0.7 on 2024-11-28 10:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_product_synced"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="synced",
            new_name="synced_at",
        ),
    ]
