# Generated by Django 5.0.7 on 2024-11-28 10:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_rename_synced_product_synced_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="synced_at",
        ),
    ]
