# Generated by Django 5.0.7 on 2024-11-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gallery", "0003_remove_image_original_image_ext_id_image_image_and_more"),
        ("product", "0009_remove_product_synced_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                related_name="product_images",
                to="gallery.image",
                verbose_name="Изображения",
            ),
        ),
    ]
