# This is the default configuration file for the server.
# Use only for getting ssl/tls certificates from certbot

server {
    listen 80;
    server_name astrotech-spaceapp.space;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}