# Generated by Django 5.0.7 on 2024-10-21 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="C:\\Users\\user\\Desktop\\project\\marketplace-server\\media/avatar/",
                verbose_name="Аватар",
            ),
        ),
    ]
