# Generated by Django 5.0.7 on 2024-11-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0002_alter_profile_avatar"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                blank=True, null=True, upload_to="media//avatar/", verbose_name="Аватар"
            ),
        ),
    ]
