# Generated by Django 5.0.7 on 2024-10-08 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorization", "0004_usertempdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertempdata",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Пользователь",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
