# Generated by Django 5.0.7 on 2024-10-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0006_alter_user_password_alter_usertempdata_user_oauth2"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertempdata",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
