# Generated by Django 5.0.7 on 2024-10-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0007_usertempdata_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertempdata",
            name="expired_time",
            field=models.DateTimeField(null=True, verbose_name="Время истечения"),
        ),
    ]
