# Generated by Django 5.0.2 on 2024-10-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authorization", "0008_alter_usertempdata_expired_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Имя"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="Фамилия"
            ),
        ),
    ]
