name: Build Production Stage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            ref: master
            ssh-key: ${{ secrets.REPOSITORY_SSH_PRIVATE_KEY }}

      - name: Login to container registry
        run: |
          echo '${{ secrets.GH_CR_PASSWORD}}' | docker login ghcr.io -u '${{ vars.GH_CR_USER }}' --password-stdin

      - name: Set-up .env file build
        run: |
          cp .env.example .env
          cat >> .env <<EOF

          # EMAIL SETTINGS VARS
          EMAIL_HOST=${{ vars.EMAIL_HOST }}
          EMAIL_HOST_USER=${{ vars.EMAIL_HOST_USER }}
          DEFAULT_EMAIL=${{ vars.DEFAULT_EMAIL }}

          # DATABASE VARS
          POSTGRES_DB=${{ vars.POSTGRES_DB }}
          POSTGRES_USER=${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

          # ENVIRONMENT
          ENVIRONMENT=${{ vars.ENVIRONMENT }}
          EOF

      - name: Build images
        run: |
          docker compose build
          docker compose push

      - name: Finish build
        run: |
          docker logout ghcr.io
          rm .env

      - name: Trigger deploy
        run: |
          curl -X POST -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.GH_TOKEN }}" \
          https://api.github.com/repos/${{ github.repository }}/dispatches \
          -d '{"event_type": "container_push"}'
