name: Build Production Stage

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
            ref: master
            ssh-key: ${{ secrets.REPOSITORY_SSH_PRIVATE_KEY }}

      - name: Login to container registry
        run: |
          echo "${{ secrets.GH_CR_PASSWORD}}" | docker login ghcr.io -u "${{ vars.GH_CR_USER }}" --password-stdin

      - name: Set-up .env file and build
        run: |
          cp .env.example .env
          cat > .env <<EOF

          # EMAIL SETTINGS VARS
          EMAIL_HOST=${{ vars.EMAIL_HOST }}
          EMAIL_HOST_USER=${{ vars.EMAIL_HOST_USER }}
          DEFAULT_EMAIL=${{ vars.DEFAULT_EMAIL }}

          # DATABASE VARS
          POSTGRES_DB=${{ vars.POSTGRES_DB }}
          POSTGRES_USER=${{ vars.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}

          # ENVIRONMENT
          ENVIRONMENT=${{ vars.ENVIRONMENT }}
          EOF

          docker compose build
          docker compose push

      - name: Finish build
        run: |
          docker logout ghcr.io
          rm .env
