name: Deploy Production

on:
  repository_dispatch:
    types: [container_push]

env:
  DOCKER_CR_USER: ${{ secrets.DOCKER_CR_USER }}
  SSH_PRIVATE_KEY: ${{ secrets.PRODUCTION_SERVER_SSH_PRIVATE_KEY }}
  DOCKER_CR_PASSWORD: ${{ secrets.DOCKER_CR_PASSWORD }}
  
  HOST_IP: ${{ vars.HOST_IP }}
  HOST_USER: ${{ vars.HOST_USER }}
  WORK_DIR: ${{ vars.WORK_DIR }}
  SSH_IDENTITY_FILE: ${{ vars.SSH_IDENTITY_FILE_PATH }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
        with:
          ref: main
          ssh-key: ${{ secrets.REPOSITORY_SSH_PRIVATE_KEY }}

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts
          ssh-keyscan -H "$HOST_IP" >> ~/.ssh/known_hosts

          echo "$SSH_PRIVATE_KEY" > '$SSH_IDENTITY_FILE'
          chmod 600 '$SSH_IDENTITY_FILE'

      - name: Copy compose files to server
        run: |
          ssh -i '$SSH_IDENTITY_FILE' "$HOST_USER@$HOST_IP" \
            "mkdir -p $WORK_DIR"

          scp -i '$SSH_IDENTITY_FILE' ./compose.deploy.yml "$HOST_USER@$HOST_IP:'$WORK_DIR/compose.deploy.yml'"

      - name: Login to server, pull containers and deploy
        run: |
          ssh "$HOST_USER@$HOST_IP" -i '$SSH_IDENTITY_FILE' \
          "
          echo "$DOCKER_CR_PASSWORD" | docker login ghcr.io -u "$DOCKER_CR_USER" --password-stdin

          docker compose -f compose.deploy.yml down
          docker compose -f compose.deploy.yml pull
          docker compose -f compose.deploy.yml up -d

          docker logout ghcr.io
          "
